"""empty message

Revision ID: 46cb62d080a7
Revises: c97f1410738a
Create Date: 2025-02-15 12:00:47.747392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cb62d080a7'
down_revision = 'c97f1410738a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_delivery', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('date_delivery')
        batch_op.drop_column('date_order')

    # ### end Alembic commands ###
