"""empty message

Revision ID: c97f1410738a
Revises: 0254d6f3d41c
Create Date: 2025-02-15 09:50:20.227870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97f1410738a'
down_revision = '0254d6f3d41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_sell', sa.Boolean(), nullable=True))
        batch_op.drop_column('in_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_venta', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('in_sell')

    # ### end Alembic commands ###
